---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  #require_chef_omnibus: 13.5.3

verifier:
  name: inspec

platforms:
  #  - name: ubuntu-16.04 # bento image wonky as of 18.02.04
  - name: debian-9
  - name: centos-7

suites:
  - name: default
    run_list:
      - recipe[chruby_install::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
